openapi: 3.0.1
info:
  title: MERLIN DB
  description: ''
  version: '1.0'
servers:
  - url: https://niaid-bpimb-apim-dev.azure-api.net
paths:
  /vendor:
    get:
      summary: Get Vendor
      description: Get Vendor
      operationId: get-vendor
      parameters:
        - name: vendorName
          in: query
          schema:
            type: ''
        - name: Content-Type
          in: header
          schema:
            enum:
              - application/json
            type: string
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]