openapi: 3.0.1
info:
  title: OTCS MCP Server
  description: ''
  version: '1.0'
servers:
  - url: https://gateway.apimdev.niaid.nih.gov/otcs-mcp
paths:
  /mcp:
    get:
      summary: mcp-get
      description: mcp-get
      operationId: mcp-get
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]