openapi: 3.0.1
info:
  title: Sandbox Test API
  version: '1.0'
servers:
  - url: https://niaid-bpimb-apim-dev.azure-api.net/sandbox-test
paths:
  /get:
    get:
      summary: Get Test
      description: Get Test
      operationId: 022b17a409a44104a9b346490597b0b8
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]