openapi: 3.0.1
info:
  title: ITPMS Chat API
  description: Import from "niaid-azure-oaipoc-api-fa" Function App
  version: '1.0'
servers:
  - url: https://gateway.apimdev.niaid.nih.gov/niaid-azure-oaipoc-api-fa
paths:
  /HttpExample:
    post:
      summary: HttpExample
      description: HttpExample
      operationId: post-httpexample
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]