openapi: 3.0.1
info:
  title: test
  version: ''
servers:
  - url: https://gateway.apimdev.niaid.nih.gov/test
paths:
  /anything/test:
    get:
      summary: Test echo
      description: Test echo
      operationId: test
      responses:
        '200':
          description: OK
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]